# Generated by Django 3.1.4 on 2022-05-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_image',
        ),
    ]
