# Generated by Django 3.1.4 on 2022-05-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_pooja'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPooja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pooja_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.pooja')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.users')),
            ],
            options={
                'verbose_name_plural': 'AssignPooja',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
