# Generated by Django 3.1.4 on 2022-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_assignpooja'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpooja',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignpooja',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignpooja',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
