# Generated by Django 4.0.1 on 2022-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_expenses_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
