# Generated by Django 4.0.1 on 2022-05-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_amount_income_inamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='INamount',
            new_name='amount',
        ),
    ]
